import Link from 'next/link';

export const metadata = {
  title: 'Terms of Service — mu8ic',
};

const Section = ({ title, children }: { title: string; children: React.ReactNode }) => (
  <section className="mb-10">
    <h2 className="mb-4 text-sm font-semibold uppercase tracking-widest text-white/40">
      {title}
    </h2>
    <div className="space-y-3 text-sm leading-relaxed text-white/60">
      {children}
    </div>
  </section>
);

export default function TermsPage() {
  return (
    <div className="min-h-screen w-full" style={{ backgroundColor: '#181818' }}>
      {/* Header */}
      <header className="fixed top-0 left-0 z-50 flex w-full items-center justify-between border-b px-8 py-4"
        style={{ borderColor: 'rgba(255,255,255,0.06)', backgroundColor: 'rgba(24,24,24,0.85)', backdropFilter: 'blur(20px)', WebkitBackdropFilter: 'blur(20px)' }}
      >
        <Link
          href="/"
          className="text-base font-bold tracking-wider text-white/90 transition-opacity hover:opacity-70"
          style={{ fontFamily: 'var(--font-schoolbell)' }}
        >
          mu8ic
        </Link>
        <Link
          href="/"
          className="text-xs text-white/30 transition-colors hover:text-white/60"
        >
          ← Back
        </Link>
      </header>

      {/* Content */}
      <main className="mx-auto max-w-2xl px-6 pb-24 pt-28">
        <div className="mb-12">
          <h1 className="text-2xl font-bold text-white/90">Terms of Service</h1>
          <p className="mt-2 text-xs text-white/25">Effective date: March 19, 2026</p>
        </div>

        <Section title="Acceptance of Terms">
          <p>
            By accessing or using mu8ic ("the Service"), you agree to be bound by these Terms of Service. If you do not agree to these terms, please do not use the Service.
          </p>
          <p>
            We reserve the right to update these terms at any time. Continued use of the Service after changes constitutes acceptance of the updated terms.
          </p>
        </Section>

        <Section title="Description of Service">
          <p>
            mu8ic is an AI-powered music generation service. Users provide text prompts and the Service generates original audio tracks using artificial intelligence. Generated music is stored in the user's personal library and can be downloaded for use.
          </p>
        </Section>

        <Section title="Account Registration">
          <p>
            You must sign in with a valid Google account to use the Service. You are responsible for maintaining the security of your account. Any activity under your account is your responsibility.
          </p>
          <p>
            You must be at least 13 years of age to use the Service. By creating an account, you represent that you meet this requirement.
          </p>
        </Section>

        <Section title="Credits and Payments">
          <p>
            The Service operates on a credit-based system. Credits are required to generate music. Credits are consumed according to the selected options (duration, number of tracks).
          </p>
          <p>
            Credits are purchased through our payment processor Polar and are non-refundable except as required by law. Credits do not expire as long as your account remains active.
          </p>
          <p>
            Credit costs per generation:
          </p>
          <ul className="ml-4 space-y-2 list-disc list-outside marker:text-white/20">
            <li>Base: 1 credit per generation</li>
            <li>2-minute duration: +1 credit</li>
            <li>3-minute duration: +2 credits</li>
            <li>Each additional track: +1 credit per track</li>
          </ul>
          <p>
            We reserve the right to modify pricing with reasonable notice.
          </p>
        </Section>

        <Section title="Intellectual Property & Generated Content">
          <p>
            <span className="text-white/80">Your content.</span> Music generated through mu8ic using your prompts is yours to use. You are granted a perpetual, non-exclusive license to use, download, and distribute the generated audio for personal and commercial purposes, including YouTube content, podcasts, and other media.
          </p>
          <p>
            <span className="text-white/80">AI-generated nature.</span> All music is generated by artificial intelligence. We make no guarantees regarding uniqueness. Similar prompts may produce similar results for different users.
          </p>
          <p>
            <span className="text-white/80">Our rights.</span> mu8ic retains rights to the platform, technology, and any improvements derived from usage patterns. We do not claim ownership of the specific audio files generated for your account.
          </p>
        </Section>

        <Section title="Prohibited Uses">
          <p>You may not use the Service to:</p>
          <ul className="ml-4 space-y-2 list-disc list-outside marker:text-white/20">
            <li>Generate content that infringes third-party intellectual property rights</li>
            <li>Attempt to reverse-engineer or extract the underlying AI models</li>
            <li>Automate or script requests in a way that disrupts the service</li>
            <li>Resell or redistribute access to the Service</li>
            <li>Use the Service for any unlawful purpose</li>
          </ul>
        </Section>

        <Section title="Service Availability">
          <p>
            We strive to maintain high availability but do not guarantee uninterrupted access. We may perform maintenance, updates, or experience downtime beyond our control. We are not liable for losses resulting from service interruptions.
          </p>
          <p>
            We reserve the right to suspend or terminate accounts that violate these terms without prior notice.
          </p>
        </Section>

        <Section title="Disclaimer of Warranties">
          <p>
            The Service is provided "as is" without warranties of any kind, express or implied. We do not warrant that the Service will be error-free, that generated music will meet your specific requirements, or that the Service will be available at any particular time.
          </p>
        </Section>

        <Section title="Limitation of Liability">
          <p>
            To the maximum extent permitted by law, mu8ic shall not be liable for any indirect, incidental, special, consequential, or punitive damages arising from your use of the Service. Our total liability to you shall not exceed the amount you paid to us in the 3 months preceding the claim.
          </p>
        </Section>

        <Section title="Governing Law">
          <p>
            These Terms are governed by the laws of the Republic of Korea, without regard to conflict of law principles. Any disputes arising from these Terms shall be subject to the exclusive jurisdiction of the courts in Seoul, Korea.
          </p>
        </Section>

        <Section title="Contact">
          <p>
            For questions about these Terms of Service, please contact us at{' '}
            <a
              href="mailto:support@mu8ic.app"
              className="text-white/50 underline decoration-dotted hover:text-white/80 transition-colors"
            >
              support@mu8ic.app
            </a>
            .
          </p>
        </Section>

        <div className="mt-16 border-t pt-8 text-xs text-white/20" style={{ borderColor: 'rgba(255,255,255,0.06)' }}>
          <div className="flex items-center justify-between">
            <span style={{ fontFamily: 'var(--font-schoolbell)' }}>mu8ic</span>
            <div className="flex gap-4">
              <Link href="/privacy" className="hover:text-white/40 transition-colors">Privacy Policy</Link>
            </div>
          </div>
        </div>
      </main>
    </div>
  );
}
